import {readFileSync,readdirSync} from "node:fs";
import {join,relative} from "node:path";

interface GitHubConfig {
  token:string;
  owner:string;
  repo:string;
  baseBranch:string;
}

interface GitHubCommit {
  sha:string;
}

interface GitHubTree {
  sha:string;
}

interface GitHubPullRequest {
  number:number;
  html_url:string;
  head:{sha:string};
}

function config():GitHubConfig {
  const token=process.env.GITHUB_TOKEN;
  const repository=process.env.GITHUB_REPOSITORY||"travellerswiss01/V0.1";
  const [owner,repo]=repository.split("/");
  if(!token) throw new Error("GitHub publishing requires GITHUB_TOKEN.");
  if(!owner||!repo) throw new Error("GITHUB_REPOSITORY must use owner/repo format.");
  return {token,owner,repo,baseBranch:process.env.GITHUB_BASE_BRANCH||"main"};
}

async function github<T>(path:string,init:RequestInit={}):Promise<T> {
  const c=config();
  const response=await fetch(`https://api.github.com${path}`,{
    ...init,
    headers:{
      accept:"application/vnd.github+json",
      authorization:`Bearer ${c.token}`,
      "x-github-api-version":"2022-11-28",
      "content-type":"application/json",
      ...(init.headers||{})
    }
  });
  const body=await response.text();
  if(!response.ok) throw new Error(`GitHub API ${response.status}: ${body.slice(0,500)}`);
  return JSON.parse(body) as T;
}

function files(root:string):string[] {
  const result:string[]=[];
  const visit=(dir:string)=>{
    for(const entry of readdirSync(dir,{withFileTypes:true})){
      const full=join(dir,entry.name);
      if(entry.isDirectory()) visit(full);
      else result.push(relative(root,full));
    }
  };
  visit(root);
  return result.sort();
}

function branchName(decisionId:string):string {
  return `agent/product-${decisionId.slice(0,8)}`;
}

export async function publishWorkspaceToGitHub(
  workspace:string,
  decisionId:string,
  title:string,
  objective:string
):Promise<{branch:string;commitSha:string;prNumber:number;prUrl:string}> {
  const c=config();
  const base=await github<GitHubCommit>(`/repos/${c.owner}/${c.repo}/git/ref/heads/${c.baseBranch}`);
  const baseSha=base.sha;
  const baseCommit=await github<{sha:string;commit:{tree:{sha:string}}}>(`/repos/${c.owner}/${c.repo}/commits/${baseSha}`);
  const branch=branchName(decisionId);

  await github(`/repos/${c.owner}/${c.repo}/git/refs`,{
    method:"POST",
    body:JSON.stringify({ref:`refs/heads/${branch}`,sha:baseSha})
  });

  const treeItems=files(workspace).map(file=>({
    path:`products/${branch.slice(-8)}/${file}`,
    mode:"100644",
    type:"blob",
    content:readFileSync(join(workspace,file),"utf8")
  }));

  const tree=await github<GitHubTree>(`/repos/${c.owner}/${c.repo}/git/trees`,{
    method:"POST",
    body:JSON.stringify({base_tree:baseCommit.commit.tree.sha,tree:treeItems})
  });

  const commit=await github<GitHubCommit>(`/repos/${c.owner}/${c.repo}/git/commits`,{
    method:"POST",
    body:JSON.stringify({
      message:`AI product prototype: ${title}`,
      tree:tree.sha,
      parents:[baseSha]
    })
  });

  await github(`/repos/${c.owner}/${c.repo}/git/refs/heads/${branch}`,{
    method:"PATCH",
    body:JSON.stringify({sha:commit.sha,force:false})
  });

  const pr=await github<GitHubPullRequest>(`/repos/${c.owner}/${c.repo}/pulls`,{
    method:"POST",
    body:JSON.stringify({
      title:`AI product prototype: ${title}`,
      head:branch,
      base:c.baseBranch,
      draft:true,
      body:[
        "## Autonomous Company V0.1",
        "",
        `Decision: ${decisionId}`,
        `Objective: ${objective}`,
        "",
        "Generated by the guarded AI coding agent.",
        "Validation must pass before this PR is considered for review."
      ].join("\n")
    })
  });

  return {branch,commitSha:commit.sha,prNumber:pr.number,prUrl:pr.html_url};
}